Fix typo
CircleCI-Public/twilio-orb pull request #2
Opened 2019-10-01 06:01 UTC by ankitjain28may

2019-10-01 06:03 UTC, ankitjain28may commented
Can you please add the #orbtoberfest label?

2019-10-01 19:24 UTC, markstonehouse commented
This is still a grammatical error. It should read "Notification from CircleCI. A critical test has failed." @ankitjain28may

2019-10-01 19:29 UTC, gep13 requested changes
As suggested by @markstonehouse

2019-10-01 19:29 UTC, gep13 commented on src/@orb.yml
> +        default: "Notification from CircleCI. A critical test is failed."
```suggestion
        default: "Notification from CircleCI. A critical test has failed."
```

2019-10-01 19:38 UTC, ankitjain28may commented
Sorry, my bad, Thanks updated :)

2019-10-08 11:56 UTC, ankitjain28may commented
@gep13 Any updates?

2019-10-08 12:36 UTC, gep13 approved these changes
LGTM!

2019-10-08 12:36 UTC, gep13 commented
@ankitjain28may I am not in a position to merge this PR, I only reviewed it.

2019-11-15 02:33 UTC, lokst approved these changes
LGTM

2020-01-02 15:59 UTC, KyleTryon approved these changes

2020-01-02 15:59 UTC, KyleTryon commented
Thank you everyone. Merging. This will appear in the next major update.

2020-01-02 16:00 UTC, merged